# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Restore .NET Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'  # Adjust the version as necessary

    - name: Restore dependencies
      run: |
        cd src/Project.NET/Backend  # Navigate to the project directory
        dotnet restore    # Restore dependencies for the project
